/*
MySQL Data Transfer
Source Host: localhost
Source Database: mnrtsafari
Target Host: localhost
Target Database: mnrtsafari
Date: 7/3/2021 8:49:52 AM
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for afcg_assessment_town_hotel
-- ----------------------------
DROP TABLE IF EXISTS `afcg_assessment_motel`;
CREATE TABLE `afcg_assessment_motel` (
  `id` bigint(50) NOT NULL AUTO_INCREMENT,
  `assessment_id` varchar(50) DEFAULT NULL,
  `facility_id` varchar(50) DEFAULT NULL,
  `assessor_category` varchar(50) NOT NULL,
  `assessment_score` varchar(5) DEFAULT NULL,
  `location_1_0_1_text` text,
  `location_1_0_1_A` varchar(5) DEFAULT NULL,
  `location_1_0_1_B` varchar(5) DEFAULT NULL,
  `location_1_1_1_text` text,
  `location_1_1_1_A` varchar(5) DEFAULT NULL,
  `location_1_1_2_text` text,
  `location_1_1_2_A` varchar(5) DEFAULT NULL,
  `location_1_1_3_text` text,
  `location_1_1_3_A` varchar(5) DEFAULT NULL,
  `location_1_1_3_B_a` varchar(5) DEFAULT NULL,
  `location_1_1_3_B_b` varchar(5) DEFAULT NULL,
  `location_1_1_3_B_c` varchar(5) DEFAULT NULL,
  `location_1_1_3_B_d` varchar(5) DEFAULT NULL,
  `location_1_1_4_text` text,
  `location_1_1_4_A` varchar(5) DEFAULT NULL,
  `location_1_1_4_B` varchar(5) DEFAULT NULL,
  `location_1_1_4_C` varchar(5) DEFAULT NULL,
  `location_1_1_5_text` text,
  `location_1_1_5_A` varchar(5) DEFAULT NULL,
  `location_1_1_5_B` varchar(5) DEFAULT NULL,
  `location_1_1_5_C` varchar(5) DEFAULT NULL,
  `location_1_1_5_D` varchar(5) DEFAULT NULL,
  `location_1_2_1_text` text,
  `location_1_2_1_A` varchar(5) DEFAULT NULL,
  `building_2_1_1_text` text,
  `building_2_1_1_A` varchar(5) DEFAULT NULL,
  `building_2_1_2_text` text,
  `building_2_1_2_A` varchar(5) DEFAULT NULL,
  `building_2_2_1_text` text,
  `building_2_2_1_A` varchar(5) DEFAULT NULL,
  `building_2_2_1_B` varchar(5) DEFAULT NULL,
  `building_2_2_2_text` text,
  `building_2_2_2_A` varchar(5) DEFAULT NULL,
  `building_2_2_2_B` varchar(5) DEFAULT NULL,
  `building_2_2_2_C` varchar(5) DEFAULT NULL,
  `building_2_2_2_D` varchar(5) DEFAULT NULL,
  `building_2_2_2_E` varchar(5) DEFAULT NULL,
  `building_2_2_2_F` varchar(5) DEFAULT NULL,
  `building_2_2_2_G` varchar(5) DEFAULT NULL,
  `building_2_3_1_text` text,
  `building_2_3_1_A` varchar(5) DEFAULT NULL,
  `building_2_4_1_text` text,
  `building_2_4_1_A` varchar(5) DEFAULT NULL,
  `building_2_4_1_B` varchar(5) DEFAULT NULL,
  `building_2_4_1_C` varchar(5) DEFAULT NULL,
  `building_2_4_1_D` varchar(5) DEFAULT NULL,
  `building_2_4_1_E` varchar(5) DEFAULT NULL,
  `building_2_4_1_F` varchar(5) DEFAULT NULL,
  `building_2_4_1_G` varchar(5) DEFAULT NULL,
  `building_2_4_1_H` varchar(5) DEFAULT NULL,
  `building_2_4_1_I` varchar(5) DEFAULT NULL,
  `building_2_4_1_J` varchar(5) DEFAULT NULL,
  `front_office_3_1_1_text` text,
  `front_office_3_1_1_A` varchar(5) DEFAULT NULL,
  `front_office_3_1_1_B` varchar(5) DEFAULT NULL,
  `front_office_3_1_1_C` varchar(5) DEFAULT NULL,
  `front_office_3_1_1_D` varchar(5) DEFAULT NULL,
  `front_office_3_1_2_text` text,
  `front_office_3_1_2_A` varchar(5) DEFAULT NULL,
  `front_office_3_1_2_B` varchar(5) DEFAULT NULL,
  `front_office_3_1_2_C` varchar(5) DEFAULT NULL,
  `front_office_3_1_2_D` varchar(5) DEFAULT NULL,
  `front_office_3_1_2_E` varchar(5) DEFAULT NULL,
  `front_office_3_1_2_F` varchar(5) DEFAULT NULL,
  `front_office_3_2_1_text` text,
  `front_office_3_2_1_A` varchar(5) DEFAULT NULL,
  `front_office_3_2_1_B_a` varchar(5) DEFAULT NULL,
  `front_office_3_2_1_B_b` varchar(5) DEFAULT NULL,
  `front_office_3_2_1_B_c` varchar(5) DEFAULT NULL,
  `front_office_3_2_1_C_a` varchar(5) DEFAULT NULL,
  `front_office_3_2_1_C_b` varchar(5) DEFAULT NULL,
  `front_office_3_2_1_C_c` varchar(5) DEFAULT NULL,
  `front_office_3_2_1_D_a` varchar(5) DEFAULT NULL,
  `front_office_3_2_1_D_b` varchar(5) DEFAULT NULL,
  `front_office_3_2_1_D_c` varchar(5) DEFAULT NULL,
  `front_office_3_2_1_D_d` varchar(5) DEFAULT NULL,
  `front_office_3_3_1_text` text,
  `front_office_3_3_1_A` varchar(5) DEFAULT NULL,
  `front_office_3_3_1_B` varchar(5) DEFAULT NULL,
  `front_office_3_4_1_text` text,
  `front_office_3_4_1_A_a` varchar(5) DEFAULT NULL,
  `front_office_3_4_1_A_b` varchar(5) DEFAULT NULL,
  `front_office_3_4_1_A_c` varchar(5) DEFAULT NULL,
  `front_office_3_4_1_A_d` varchar(5) DEFAULT NULL,
  `front_office_3_5_1_text` text,
  `front_office_3_5_1_A` varchar(5) DEFAULT NULL,
  `front_office_3_5_1_B` varchar(5) DEFAULT NULL,
  `front_office_3_5_1_C` varchar(5) DEFAULT NULL,
  `front_office_3_6_1_text` text,
  `front_office_3_6_1_A` varchar(5) DEFAULT NULL,
  `front_office_3_6_1_B` varchar(5) DEFAULT NULL,
  `front_office_3_7_1_text` text,
  `front_office_3_7_1_A_a` varchar(5) DEFAULT NULL,
  `front_office_3_7_1_A_b` varchar(5) DEFAULT NULL,
  `front_office_3_7_1_A_c` varchar(5) DEFAULT NULL,
  `front_office_3_7_1_B_a` varchar(5) DEFAULT NULL,
  `front_office_3_7_1_B_b` varchar(5) DEFAULT NULL,
  `front_office_3_7_1_B_c` varchar(5) DEFAULT NULL,
  `front_office_3_8_1_text` text,
  `front_office_3_8_1_A` varchar(5) DEFAULT NULL,
  `front_office_3_8_1_B` varchar(5) DEFAULT NULL,
  `front_office_3_8_1_C` varchar(5) DEFAULT NULL,
  `front_office_3_8_1_D` varchar(5) DEFAULT NULL,
  `front_office_3_8_1_E` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_0_1_text` text,
  `lobby_lounge_other_public_areas_4_0_1_A` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_0_1_B` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_0_1_C` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_0_1_D` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_0_1_E` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_0_1_F` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_1_1_text` text,
  `lobby_lounge_other_public_areas_4_1_1_A` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_1_1_B_a` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_1_1_B_b` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_1_1_B_c` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_1_1_B_d` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_1_1_C` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_2_1_text` text,
  `lobby_lounge_other_public_areas_4_2_1_A` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_2_1_B` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_2_1_C` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_2_1_D_a` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_2_1_D_b` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_2_1_E` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_2_1_F` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_2_1_G` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_3_1_text` text,
  `lobby_lounge_other_public_areas_4_3_1_A` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_3_1_B` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_4_1_text` text,
  `lobby_lounge_other_public_areas_4_4_1_A` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_4_1_B` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_4_1_C` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_4_1_D` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_4_1_E` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_4_1_F` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_5_1_text` text,
  `lobby_lounge_other_public_areas_4_5_1_A` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_5_1_B` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_5_1_C` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_6_1_text` text,
  `lobby_lounge_other_public_areas_4_6_1_A` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_6_1_B_a` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_6_1_B_b` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_6_1_B_c` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_6_1_B_d` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_6_1_B_e` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_6_1_B_f` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_6_1_C` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_7_1_text` text,
  `lobby_lounge_other_public_areas_4_7_1_A` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_7_1_B_a` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_7_1_B_b` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_7_1_B_c` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_7_1_C_a` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_7_1_C_b` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_7_1_C_c` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_7_1_D_a` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_7_1_D_b` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_7_1_D_c` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_7_1_D_d` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_8_1_text` text,
  `lobby_lounge_other_public_areas_4_8_1_A` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_8_1_B` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_8_1_C` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_8_1_D` varchar(5) DEFAULT NULL,
  `lobby_lounge_other_public_areas_4_9_1_text` text,
  `lobby_lounge_other_public_areas_4_9_1_A` varchar(5) DEFAULT NULL,
  `restaurants_5_1_1_text` text,
  `restaurants_5_1_1_A` varchar(5) DEFAULT NULL,
  `restaurants_5_1_1_B` varchar(5) DEFAULT NULL,
  `restaurants_5_1_1_C` varchar(5) DEFAULT NULL,
  `restaurants_5_2_1_text` text,
  `restaurants_5_2_1_A` varchar(5) DEFAULT NULL,
  `restaurants_5_2_1_B` varchar(5) DEFAULT NULL,
  `restaurants_5_2_1_C` varchar(5) DEFAULT NULL,
  `restaurants_5_2_1_D` varchar(5) DEFAULT NULL,
  `restaurants_5_2_1_E` varchar(5) DEFAULT NULL,
  `restaurants_5_2_1_F` varchar(5) DEFAULT NULL,
  `restaurants_5_2_1_G` varchar(5) DEFAULT NULL,
  `restaurants_5_2_1_H` varchar(5) DEFAULT NULL,
  `restaurants_5_3_1_text` text,
  `restaurants_5_3_1_A` varchar(5) DEFAULT NULL,
  `restaurants_5_3_1_B` varchar(5) DEFAULT NULL,
  `restaurants_5_3_1_C` varchar(5) DEFAULT NULL,
  `restaurants_5_4_1_text` text,
  `restaurants_5_4_1_A` varchar(5) DEFAULT NULL,
  `restaurants_5_4_1_B` varchar(5) DEFAULT NULL,
  `restaurants_5_4_1_C` varchar(5) DEFAULT NULL,
  `restaurants_5_4_1_D` varchar(5) DEFAULT NULL,
  `restaurants_5_4_1_E` varchar(5) DEFAULT NULL,
  `restaurants_5_5_1_text` text,
  `restaurants_5_5_1_A` varchar(5) DEFAULT NULL,
  `restaurants_5_5_1_B` varchar(5) DEFAULT NULL,
  `restaurants_5_5_1_C` varchar(5) DEFAULT NULL,
  `restaurants_5_5_1_D` varchar(5) DEFAULT NULL,
  `restaurants_5_5_1_E_a` varchar(5) DEFAULT NULL,
  `restaurants_5_5_1_E_b` varchar(5) DEFAULT NULL,
  `restaurants_5_5_1_E_c` varchar(5) DEFAULT NULL,
  `restaurants_5_5_1_E_d` varchar(5) DEFAULT NULL,
  `restaurants_5_5_1_F` varchar(5) DEFAULT NULL,
  `restaurants_5_5_1_G_a` varchar(5) DEFAULT NULL,
  `restaurants_5_5_1_G_b` varchar(5) DEFAULT NULL,
  `restaurants_5_5_1_G_c` varchar(5) DEFAULT NULL,
  `restaurants_5_5_1_H` varchar(5) DEFAULT NULL,
  `restaurants_5_5_1_I` varchar(5) DEFAULT NULL,
  `restaurants_5_6_1_text` text,
  `restaurants_5_6_1_A` varchar(5) DEFAULT NULL,
  `restaurants_5_6_1_B` varchar(5) DEFAULT NULL,
  `restaurants_5_6_1_C` varchar(5) DEFAULT NULL,
  `restaurants_5_6_1_D` varchar(5) DEFAULT NULL,
  `restaurants_5_7_1_text` text,
  `restaurants_5_7_1_A` varchar(5) DEFAULT NULL,
  `restaurants_5_7_1_B` varchar(5) DEFAULT NULL,
  `restaurants_5_7_1_C` varchar(5) DEFAULT NULL,
  `restaurants_5_8_1_text` text,
  `restaurants_5_8_1_A` varchar(5) DEFAULT NULL,
  `restaurants_5_8_1_B` varchar(5) DEFAULT NULL,
  `bar_6_1_1_text` text,
  `bar_6_1_1_A` varchar(5) DEFAULT NULL,
  `bar_6_1_1_B_a` varchar(5) DEFAULT NULL,
  `bar_6_1_1_B_b` varchar(5) DEFAULT NULL,
  `bar_6_1_1_B_c` varchar(5) DEFAULT NULL,
  `bar_6_1_1_C` varchar(5) DEFAULT NULL,
  `bar_6_1_1_D_a` varchar(5) DEFAULT NULL,
  `bar_6_1_1_D_b` varchar(5) DEFAULT NULL,
  `bar_6_1_1_D_c` varchar(5) DEFAULT NULL,
  `bar_6_1_1_E` varchar(5) DEFAULT NULL,
  `bar_6_1_1_F` varchar(5) DEFAULT NULL,
  `bar_6_1_1_G` varchar(5) DEFAULT NULL,
  `bar_6_2_1_text` text,
  `bar_6_2_1_A` varchar(5) DEFAULT NULL,
  `bar_6_2_1_B` varchar(5) DEFAULT NULL,
  `bar_6_2_1_C` varchar(5) DEFAULT NULL,
  `bar_6_2_1_D` varchar(5) DEFAULT NULL,
  `bar_6_2_1_E` varchar(5) DEFAULT NULL,
  `bar_6_2_1_F` varchar(5) DEFAULT NULL,
  `bar_6_2_1_G` varchar(5) DEFAULT NULL,
  `bar_6_2_1_H` varchar(5) DEFAULT NULL,
  `bar_6_2_1_I` varchar(5) DEFAULT NULL,
  `bar_6_2_1_J` varchar(5) DEFAULT NULL,
  `bar_6_3_1_text` text,
  `bar_6_3_1_A` varchar(5) DEFAULT NULL,
  `bar_6_3_1_B` varchar(5) DEFAULT NULL,
  `bar_6_3_1_C` varchar(5) DEFAULT NULL,
  `bar_6_3_1_D` varchar(5) DEFAULT NULL,
  `bar_6_4_1_text` text,
  `bar_6_4_1_A` varchar(5) DEFAULT NULL,
  `bar_6_4_1_B` varchar(5) DEFAULT NULL,
  `bar_6_4_1_C` varchar(5) DEFAULT NULL,
  `bar_6_4_1_D` varchar(5) DEFAULT NULL,
  `bar_6_4_1_E_a` varchar(5) DEFAULT NULL,
  `bar_6_4_1_E_b` varchar(5) DEFAULT NULL,
  `bar_6_4_1_E_c` varchar(5) DEFAULT NULL,
  `bar_6_4_1_E_d` varchar(5) DEFAULT NULL,
  `bar_6_4_1_E_e` varchar(5) DEFAULT NULL,
  `bar_6_4_1_E_f` varchar(5) DEFAULT NULL,
  `bar_6_4_1_E_g` varchar(5) DEFAULT NULL,
  `bar_6_4_1_E_h` varchar(5) DEFAULT NULL,
  `bar_6_4_1_F` varchar(5) DEFAULT NULL,
  `bar_6_4_1_G` varchar(5) DEFAULT NULL,
  `bar_6_4_1_H` varchar(5) DEFAULT NULL,
  `bar_6_4_1_I` varchar(5) DEFAULT NULL,
  `bar_6_5_1_text` text,
  `bar_6_5_1_A` varchar(5) DEFAULT NULL,
  `bar_6_5_1_B` varchar(5) DEFAULT NULL,
  `bar_6_5_1_C` varchar(5) DEFAULT NULL,
  `bar_6_6_1_text` text,
  `bar_6_6_1_A` varchar(5) DEFAULT NULL,
  `bar_6_6_1_B` varchar(5) DEFAULT NULL,
  `bar_6_6_1_C` varchar(5) DEFAULT NULL,
  `bar_6_7_1_text` text,
  `bar_6_7_1_A` varchar(5) DEFAULT NULL,
  `bar_6_7_1_B` varchar(5) DEFAULT NULL,
  `bar_6_7_1_C` varchar(5) DEFAULT NULL,
  `kitchen_7_1_1_text` text,
  `kitchen_7_1_1_A` varchar(5) DEFAULT NULL,
  `kitchen_7_2_1_text` text,
  `kitchen_7_2_1_A` varchar(5) DEFAULT NULL,
  `kitchen_7_2_1_B` varchar(5) DEFAULT NULL,
  `kitchen_7_2_1_C` varchar(5) DEFAULT NULL,
  `kitchen_7_3_1_text` text,
  `kitchen_7_3_1_A` varchar(5) DEFAULT NULL,
  `kitchen_7_3_1_B` varchar(5) DEFAULT NULL,
  `kitchen_7_3_1_C` varchar(5) DEFAULT NULL,
  `kitchen_7_4_1_text` text,
  `kitchen_7_4_1_A` varchar(5) DEFAULT NULL,
  `kitchen_7_4_1_B` varchar(5) DEFAULT NULL,
  `kitchen_7_4_1_C` varchar(5) DEFAULT NULL,
  `kitchen_7_5_1_text` text,
  `kitchen_7_5_1_A` varchar(5) DEFAULT NULL,
  `kitchen_7_5_1_B` varchar(5) DEFAULT NULL,
  `kitchen_7_5_1_C` varchar(5) DEFAULT NULL,
  `kitchen_7_5_1_D` varchar(5) DEFAULT NULL,
  `kitchen_7_5_1_E` varchar(5) DEFAULT NULL,
  `kitchen_7_5_1_F` varchar(5) DEFAULT NULL,
  `kitchen_7_5_1_G` varchar(5) DEFAULT NULL,
  `kitchen_7_5_1_H` varchar(5) DEFAULT NULL,
  `kitchen_7_5_1_I` varchar(5) DEFAULT NULL,
  `kitchen_7_6_1_text` text,
  `kitchen_7_6_1_A` varchar(5) DEFAULT NULL,
  `kitchen_7_6_1_B` varchar(5) DEFAULT NULL,
  `kitchen_7_6_1_C` varchar(5) DEFAULT NULL,
  `kitchen_7_6_1_D` varchar(5) DEFAULT NULL,
  `kitchen_7_6_1_E` varchar(5) DEFAULT NULL,
  `kitchen_7_6_1_F` varchar(5) DEFAULT NULL,
  `kitchen_7_6_1_G` varchar(5) DEFAULT NULL,
  `kitchen_7_7_1_text` text,
  `kitchen_7_7_1_A` varchar(5) DEFAULT NULL,
  `kitchen_7_7_1_B` varchar(5) DEFAULT NULL,
  `kitchen_7_7_1_C` varchar(5) DEFAULT NULL,
  `kitchen_7_7_1_D` varchar(5) DEFAULT NULL,
  `kitchen_7_7_1_E` varchar(5) DEFAULT NULL,
  `kitchen_7_8_1_text` text,
  `kitchen_7_8_1_A` varchar(5) DEFAULT NULL,
  `kitchen_7_8_1_B` varchar(5) DEFAULT NULL,
  `kitchen_7_8_1_C_a` varchar(5) DEFAULT NULL,
  `kitchen_7_8_1_C_b` varchar(5) DEFAULT NULL,
  `kitchen_7_8_1_D` varchar(5) DEFAULT NULL,
  `kitchen_7_8_1_E` varchar(5) DEFAULT NULL,
  `kitchen_7_8_1_F` varchar(5) DEFAULT NULL,
  `kitchen_7_8_1_G` varchar(5) DEFAULT NULL,
  `kitchen_7_8_1_H` varchar(5) DEFAULT NULL,
  `kitchen_7_9_1_text` text,
  `kitchen_7_9_1_A` varchar(5) DEFAULT NULL,
  `kitchen_7_9_1_B` varchar(5) DEFAULT NULL,
  `kitchen_7_9_1_C` varchar(5) DEFAULT NULL,
  `kitchen_7_9_1_D` varchar(5) DEFAULT NULL,
  `kitchen_7_9_1_E` varchar(5) DEFAULT NULL,
  `kitchen_7_10_1_text` text,
  `kitchen_7_10_1_A_a` varchar(5) DEFAULT NULL,
  `kitchen_7_10_1_A_b` varchar(5) DEFAULT NULL,
  `kitchen_7_10_1_A_c` varchar(5) DEFAULT NULL,
  `kitchen_7_10_1_A_d` varchar(5) DEFAULT NULL,
  `kitchen_7_10_1_B` varchar(5) DEFAULT NULL,
  `kitchen_7_10_1_C` varchar(5) DEFAULT NULL,
  `kitchen_7_10_1_D` varchar(5) DEFAULT NULL,
  `kitchen_7_10_1_E` varchar(5) DEFAULT NULL,
  `kitchen_7_10_1_F` varchar(5) DEFAULT NULL,
  `kitchen_7_10_1_G` varchar(5) DEFAULT NULL,
  `kitchen_7_11_1_text` text,
  `kitchen_7_11_1_A_a` varchar(5) DEFAULT NULL,
  `kitchen_7_11_1_A_b` varchar(5) DEFAULT NULL,
  `kitchen_7_11_1_A_c` varchar(5) DEFAULT NULL,
  `kitchen_7_11_1_B` varchar(5) DEFAULT NULL,
  `kitchen_7_11_1_C_a` varchar(5) DEFAULT NULL,
  `kitchen_7_11_1_C_b` varchar(5) DEFAULT NULL,
  `kitchen_7_11_1_C_c` varchar(5) DEFAULT NULL,
  `kitchen_7_11_1_C_d` varchar(5) DEFAULT NULL,
  `kitchen_7_11_1_C_e` varchar(5) DEFAULT NULL,
  `kitchen_7_11_1_D_a` varchar(5) DEFAULT NULL,
  `kitchen_7_11_1_D_b` varchar(5) DEFAULT NULL,
  `kitchen_7_11_1_E` varchar(5) DEFAULT NULL,
  `kitchen_7_11_1_F` varchar(5) DEFAULT NULL,
  `guest_rooms_8_1_1_text` text,
  `guest_rooms_8_1_1_A` varchar(5) DEFAULT NULL,
  `guest_rooms_8_2_1_text` text,
  `guest_rooms_8_2_1_A` varchar(5) DEFAULT NULL,
  `guest_rooms_8_2_1_B` varchar(5) DEFAULT NULL,
  `guest_rooms_8_3_1_text` text,
  `guest_rooms_8_3_1_A_a` varchar(5) DEFAULT NULL,
  `guest_rooms_8_3_1_A_b` varchar(5) DEFAULT NULL,
  `guest_rooms_8_3_1_A_c` varchar(5) DEFAULT NULL,
  `guest_rooms_8_3_1_A_d` varchar(5) DEFAULT NULL,
  `guest_rooms_8_3_1_A_e` varchar(5) DEFAULT NULL,
  `guest_rooms_8_3_1_A_f` varchar(5) DEFAULT NULL,
  `guest_rooms_8_3_1_A_g` varchar(5) DEFAULT NULL,
  `guest_rooms_8_3_1_A_h` varchar(5) DEFAULT NULL,
  `guest_rooms_8_3_1_A_i` varchar(5) DEFAULT NULL,
  `guest_rooms_8_3_1_A_j` varchar(5) DEFAULT NULL,
  `guest_rooms_8_3_1_A_k` varchar(5) DEFAULT NULL,
  `guest_rooms_8_3_1_A_l` varchar(5) DEFAULT NULL,
  `guest_rooms_8_3_1_A_m` varchar(5) DEFAULT NULL,
  `guest_rooms_8_3_1_A_n` varchar(5) DEFAULT NULL,
  `guest_rooms_8_3_1_A_o` varchar(5) DEFAULT NULL,
  `guest_rooms_8_3_1_A_p` varchar(5) DEFAULT NULL,
  `guest_rooms_8_3_1_B` varchar(5) DEFAULT NULL,
  `guest_rooms_8_4_1_text` text,
  `guest_rooms_8_4_1_A` varchar(5) DEFAULT NULL,
  `guest_rooms_8_4_1_B_a` varchar(5) DEFAULT NULL,
  `guest_rooms_8_4_1_B_b` varchar(5) DEFAULT NULL,
  `guest_rooms_8_4_1_B_c` varchar(5) DEFAULT NULL,
  `guest_rooms_8_4_1_B_d` varchar(5) DEFAULT NULL,
  `guest_rooms_8_4_1_C` varchar(5) DEFAULT NULL,
  `guest_rooms_8_4_1_D` varchar(5) DEFAULT NULL,
  `guest_rooms_8_5_1_text` text,
  `guest_rooms_8_5_1_A` varchar(5) DEFAULT NULL,
  `guest_rooms_8_5_1_B` varchar(5) DEFAULT NULL,
  `guest_rooms_8_6_1_text` text,
  `guest_rooms_8_6_1_A` varchar(5) DEFAULT NULL,
  `guest_rooms_8_6_1_B` varchar(5) DEFAULT NULL,
  `guest_rooms_8_6_1_C` varchar(5) DEFAULT NULL,
  `guest_rooms_8_6_1_D` varchar(5) DEFAULT NULL,
  `guest_rooms_8_6_1_E` varchar(5) DEFAULT NULL,
  `guest_rooms_8_7_1_text` text,
  `guest_rooms_8_7_1_A` varchar(5) DEFAULT NULL,
  `guest_rooms_8_7_1_B` varchar(5) DEFAULT NULL,
  `guest_rooms_8_7_1_C` varchar(5) DEFAULT NULL,
  `guest_rooms_8_7_1_D` varchar(5) DEFAULT NULL,
  `guest_rooms_8_7_1_E` varchar(5) DEFAULT NULL,
  `guest_rooms_8_8_1_text` text,
  `guest_rooms_8_8_1_A` varchar(5) DEFAULT NULL,
  `guest_rooms_8_8_1_B_a` varchar(5) DEFAULT NULL,
  `guest_rooms_8_8_1_B_b` varchar(5) DEFAULT NULL,
  `guest_rooms_8_8_1_B_c` varchar(5) DEFAULT NULL,
  `guest_rooms_8_8_1_B_d` varchar(5) DEFAULT NULL,
  `guest_rooms_8_8_1_B_e` varchar(5) DEFAULT NULL,
  `guest_rooms_8_8_1_B_f` varchar(5) DEFAULT NULL,
  `guest_rooms_8_8_1_C_a` varchar(5) DEFAULT NULL,
  `guest_rooms_8_8_1_C_b` varchar(5) DEFAULT NULL,
  `guest_rooms_8_8_1_D` varchar(5) DEFAULT NULL,
  `guest_rooms_8_9_1_text` text,
  `guest_rooms_8_9_1_A` varchar(5) DEFAULT NULL,
  `guest_rooms_8_9_1_B` varchar(5) DEFAULT NULL,
  `guest_rooms_8_10_1_text` text,
  `guest_rooms_8_10_1_A_a` varchar(5) DEFAULT NULL,
  `guest_rooms_8_10_1_A_b` varchar(5) DEFAULT NULL,
  `guest_rooms_8_10_1_A_c` varchar(5) DEFAULT NULL,
  `guest_rooms_8_10_1_A_d` varchar(5) DEFAULT NULL,
  `guest_rooms_8_10_1_A_e` varchar(5) DEFAULT NULL,
  `guest_rooms_8_10_1_B_a` varchar(5) DEFAULT NULL,
  `guest_rooms_8_10_1_B_b` varchar(5) DEFAULT NULL,
  `guest_rooms_8_10_1_B_c` varchar(5) DEFAULT NULL,
  `guest_rooms_8_10_1_B_d` varchar(5) DEFAULT NULL,
  `guest_rooms_8_10_1_C` varchar(5) DEFAULT NULL,
  `guest_rooms_8_11_1_text` text,
  `guest_rooms_8_11_1_A` varchar(5) DEFAULT NULL,
  `guest_rooms_8_11_1_B` varchar(5) DEFAULT NULL,
  `guest_rooms_8_11_1_C_a` varchar(5) DEFAULT NULL,
  `guest_rooms_8_11_1_C_b` varchar(5) DEFAULT NULL,
  `guest_rooms_8_11_1_C_c` varchar(5) DEFAULT NULL,
  `guest_rooms_8_11_1_D` varchar(5) DEFAULT NULL,
  `guest_rooms_8_11_1_E` varchar(5) DEFAULT NULL,
  `guest_rooms_8_12_1_text` text,
  `guest_rooms_8_12_1_A` varchar(5) DEFAULT NULL,
  `guest_rooms_8_12_1_B` varchar(5) DEFAULT NULL,
  `guest_rooms_8_12_1_C` varchar(5) DEFAULT NULL,
  `guest_rooms_8_13_1_text` text,
  `guest_rooms_8_13_1_A` varchar(5) DEFAULT NULL,
  `guest_rooms_8_13_1_B_a` varchar(5) DEFAULT NULL,
  `guest_rooms_8_13_1_B_b` varchar(5) DEFAULT NULL,
  `guest_rooms_8_13_1_B_c` varchar(5) DEFAULT NULL,
  `guest_rooms_8_13_1_C` varchar(5) DEFAULT NULL,
  `guest_rooms_8_14_1_text` text,
  `guest_rooms_8_14_1_A_a` varchar(5) DEFAULT NULL,
  `guest_rooms_8_14_1_A_b` varchar(5) DEFAULT NULL,
  `guest_rooms_8_14_1_A_c` varchar(5) DEFAULT NULL,
  `guest_rooms_8_14_1_A_d` varchar(5) DEFAULT NULL,
  `guest_rooms_8_14_1_A_e` varchar(5) DEFAULT NULL,
  `guest_rooms_8_14_1_A_f` varchar(5) DEFAULT NULL,
  `guest_rooms_8_14_1_A_g` varchar(5) DEFAULT NULL,
  `guest_rooms_8_14_1_A_h` varchar(5) DEFAULT NULL,
  `guest_rooms_8_14_1_A_i` varchar(5) DEFAULT NULL,
  `guest_rooms_8_14_1_A_j` varchar(5) DEFAULT NULL,
  `guest_rooms_8_14_1_A_k` varchar(5) DEFAULT NULL,
  `guest_rooms_8_14_1_A_l` varchar(5) DEFAULT NULL,
  `guest_rooms_8_14_1_A_m` varchar(5) DEFAULT NULL,
  `guest_rooms_8_14_1_A_n` varchar(5) DEFAULT NULL,
  `guest_rooms_8_14_1_A_o` varchar(5) DEFAULT NULL,
  `guest_rooms_8_14_1_A_p` varchar(5) DEFAULT NULL,
  `guest_rooms_8_14_1_A_q` varchar(5) DEFAULT NULL,
  `guest_rooms_8_14_1_B` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_1_1_text` text,
  `guest_bathrooms_9_1_1_A` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_1_1_B` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_1_1_C` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_text` text,
  `guest_bathrooms_9_2_1_A_a` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_A_b` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_A_c` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_A_d` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_A_e` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_A_f` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_A_g` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_A_h` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_A_i` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_A_j` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_A_k` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_A_l` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_A_m` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_A_n` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_A_o` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_A_p` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_A_q` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_A_r` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_A_s` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_A_t` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_A_u` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_B` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_2_1_C` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_3_1_text` text,
  `guest_bathrooms_9_3_1_A` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_3_1_B` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_3_1_C` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_3_1_D` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_3_1_E` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_3_1_F` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_4_1_text` text,
  `guest_bathrooms_9_4_1_A_a` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_4_1_A_b` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_4_1_A_c` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_4_1_A_d` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_4_1_A_e` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_4_1_B` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_4_1_C` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_4_1_D` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_4_1_E` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_4_1_F` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_5_1_text` text,
  `guest_bathrooms_9_5_1_A` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_5_1_B` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_5_1_C` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_5_1_D` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_6_1_text` text,
  `guest_bathrooms_9_6_1_A` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_6_1_B` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_6_1_C` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_7_1_text` text,
  `guest_bathrooms_9_7_1_A_a` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_7_1_A_b` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_7_1_A_c` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_7_1_A_d` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_7_1_A_e` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_7_1_A_f` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_7_1_B` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_7_1_C` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_8_1_text` text,
  `guest_bathrooms_9_8_1_A` varchar(5) DEFAULT NULL,
  `guest_bathrooms_9_8_1_B` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_1_1_text` text,
  `hygiene_and_sanitation_10_1_1_A` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_1_1_B` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_1_1_C` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_1_1_D_a` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_1_1_D_b` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_1_1_D_c` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_1_1_D_d` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_1_1_D_e` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_1_1_D_f` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_1_1_E` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_1_1_F` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_1_1_G` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_1_1_H` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_1_1_I_a` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_1_1_I_b` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_1_1_I_c` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_1_1_I_d` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_1_1_I_e` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_1_1_J` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_1_1_K` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_2_1_text` text,
  `hygiene_and_sanitation_10_2_1_A` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_2_1_B` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_2_1_C` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_2_1_D` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_2_1_E_a` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_2_1_E_b` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_2_1_E_c` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_2_1_E_d` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_2_1_E_e` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_2_1_E_f` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_2_1_E_g` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_2_1_E_h` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_2_1_E_i` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_2_1_F` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_2_1_G` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_2_1_H_a` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_2_1_H_b` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_2_1_H_c` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_2_1_H_d` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_2_1_I` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_2_1_J` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_3_1_text` text,
  `hygiene_and_sanitation_10_3_1_A` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_3_1_B` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_3_1_C` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_3_1_D` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_3_1_E` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_3_1_F` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_4_1_text` text,
  `hygiene_and_sanitation_10_4_1_A` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_4_1_B` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_4_1_C` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_5_1_text` text,
  `hygiene_and_sanitation_10_5_1_A` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_5_1_B` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_6_1_text` text,
  `hygiene_and_sanitation_10_6_1_A` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_6_1_B_a` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_6_1_B_b` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_6_1_C` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_7_1_text` text,
  `hygiene_and_sanitation_10_7_1_A` varchar(5) DEFAULT NULL,
  `hygiene_and_sanitation_10_7_1_B` varchar(5) DEFAULT NULL,
  `safety_and_security_11_1_1_text` text,
  `safety_and_security_11_1_1_A` varchar(5) DEFAULT NULL,
  `safety_and_security_11_1_1_B` varchar(5) DEFAULT NULL,
  `safety_and_security_11_1_1_C` varchar(5) DEFAULT NULL,
  `safety_and_security_11_1_1_D` varchar(5) DEFAULT NULL,
  `safety_and_security_11_1_1_E_a` varchar(5) DEFAULT NULL,
  `safety_and_security_11_1_1_E_b` varchar(5) DEFAULT NULL,
  `safety_and_security_11_1_1_E_c` varchar(5) DEFAULT NULL,
  `safety_and_security_11_1_1_E_d` varchar(5) DEFAULT NULL,
  `safety_and_security_11_1_1_E_e` varchar(5) DEFAULT NULL,
  `safety_and_security_11_1_1_E_f` varchar(5) DEFAULT NULL,
  `safety_and_security_11_1_1_E_g` varchar(5) DEFAULT NULL,
  `safety_and_security_11_1_1_F` varchar(5) DEFAULT NULL,
  `safety_and_security_11_1_1_G` varchar(5) DEFAULT NULL,
  `safety_and_security_11_1_1_H` varchar(5) DEFAULT NULL,
  `safety_and_security_11_1_1_I` varchar(5) DEFAULT NULL,
  `safety_and_security_11_2_1_text` text,
  `safety_and_security_11_2_1_A` varchar(5) DEFAULT NULL,
  `safety_and_security_11_2_1_B` varchar(5) DEFAULT NULL,
  `safety_and_security_11_3_1_text` text,
  `safety_and_security_11_3_1_A` varchar(5) DEFAULT NULL,
  `safety_and_security_11_3_1_B` varchar(5) DEFAULT NULL,
  `safety_and_security_11_3_1_C` varchar(5) DEFAULT NULL,
  `safety_and_security_11_3_1_D` varchar(5) DEFAULT NULL,
  `safety_and_security_11_3_1_E` varchar(5) DEFAULT NULL,
  `safety_and_security_11_3_1_F` varchar(5) DEFAULT NULL,
  `safety_and_security_11_3_1_G` varchar(5) DEFAULT NULL,
  `safety_and_security_11_3_1_H` varchar(5) DEFAULT NULL,
  `safety_and_security_11_4_1_text` text,
  `safety_and_security_11_4_1_A` varchar(5) DEFAULT NULL,
  `safety_and_security_11_4_1_B` varchar(5) DEFAULT NULL,
  `safety_and_security_11_4_1_C` varchar(5) DEFAULT NULL,
  `safety_and_security_11_5_1_text` text,
  `safety_and_security_11_5_1_A` varchar(5) DEFAULT NULL,
  `safety_and_security_11_5_1_B` varchar(5) DEFAULT NULL,
  `safety_and_security_11_5_1_C` varchar(5) DEFAULT NULL,
  `safety_and_security_11_5_1_D` varchar(5) DEFAULT NULL,
  `safety_and_security_11_5_1_E` varchar(5) DEFAULT NULL,
  `safety_and_security_11_6_1_text` text,
  `safety_and_security_11_6_1_A` varchar(5) DEFAULT NULL,
  `safety_and_security_11_6_1_B` varchar(5) DEFAULT NULL,
  `safety_and_security_11_6_1_C` varchar(5) DEFAULT NULL,
  `sundry_services_12_1_1_text` text,
  `sundry_services_12_1_1_A` varchar(5) DEFAULT NULL,
  `sundry_services_12_1_1_B` varchar(5) DEFAULT NULL,
  `sundry_services_12_1_1_C` varchar(5) DEFAULT NULL,
  `sundry_services_12_2_1_text` text,
  `sundry_services_12_2_1_A` varchar(5) DEFAULT NULL,
  `sundry_services_12_3_1_text` text,
  `sundry_services_12_3_1_A` varchar(5) DEFAULT NULL,
  `sundry_services_12_4_1_text` text,
  `sundry_services_12_4_1_A` varchar(5) DEFAULT NULL,
  `sundry_services_12_4_1_B` varchar(5) DEFAULT NULL,
  `sundry_services_12_4_1_C` varchar(5) DEFAULT NULL,
  `sundry_services_12_4_1_D` varchar(5) DEFAULT NULL,
  `human_resources_13_1_1_text` text,
  `human_resources_13_1_1_A` varchar(5) DEFAULT NULL,
  `human_resources_13_1_1_B` varchar(5) DEFAULT NULL,
  `human_resources_13_1_1_C` varchar(5) DEFAULT NULL,
  `human_resources_13_1_1_D` varchar(5) DEFAULT NULL,
  `human_resources_13_1_1_E_a` varchar(5) DEFAULT NULL,
  `human_resources_13_1_1_E_b` varchar(5) DEFAULT NULL,
  `human_resources_13_1_1_E_c` varchar(5) DEFAULT NULL,
  `human_resources_13_1_1_E_d` varchar(5) DEFAULT NULL,
  `human_resources_13_1_1_E_e` varchar(5) DEFAULT NULL,
  `human_resources_13_2_1_text` text,
  `human_resources_13_2_1_A` varchar(5) DEFAULT NULL,
  `human_resources_13_2_1_B` varchar(5) DEFAULT NULL,
  `human_resources_13_3_1_text` text,
  `human_resources_13_3_1_A` varchar(5) DEFAULT NULL,
  `human_resources_13_3_1_B` varchar(5) DEFAULT NULL,
  `human_resources_13_4_1_text` text,
  `human_resources_13_4_1_A_a` varchar(5) DEFAULT NULL,
  `human_resources_13_4_1_A_b` varchar(5) DEFAULT NULL,
  `human_resources_13_4_1_A_c` varchar(5) DEFAULT NULL,
  `human_resources_13_4_1_B_a` varchar(5) DEFAULT NULL,
  `human_resources_13_4_1_B_b` varchar(5) DEFAULT NULL,
  `human_resources_13_4_1_B_c` varchar(5) DEFAULT NULL,
  `human_resources_13_4_1_C_a` varchar(5) DEFAULT NULL,
  `human_resources_13_4_1_C_b` varchar(5) DEFAULT NULL,
  `human_resources_13_4_1_C_c` varchar(5) DEFAULT NULL,
  `human_resources_13_5_1_text` text,
  `human_resources_13_5_1_A` varchar(5) DEFAULT NULL,
  `human_resources_13_6_1_text` text,
  `human_resources_13_6_1_A` varchar(5) DEFAULT NULL,
  `human_resources_13_6_1_B` varchar(5) DEFAULT NULL,
  `human_resources_13_6_1_C` varchar(5) DEFAULT NULL,
  `human_resources_13_6_1_D` varchar(5) DEFAULT NULL,
  `human_resources_13_7_1_text` text,
  `human_resources_13_7_1_A` varchar(5) DEFAULT NULL,
  `human_resources_13_7_1_B` varchar(5) DEFAULT NULL,
  `human_resources_13_7_1_C` varchar(5) DEFAULT NULL,
  `human_resources_13_7_1_D` varchar(5) DEFAULT NULL,
  `human_resources_13_7_1_E` varchar(5) DEFAULT NULL,
  `human_resources_13_7_1_F_a` varchar(5) DEFAULT NULL,
  `human_resources_13_7_1_F_b` varchar(5) DEFAULT NULL,
  `human_resources_13_8_1_text` text,
  `human_resources_13_8_1_A` varchar(5) DEFAULT NULL,
  `human_resources_13_8_1_B` varchar(5) DEFAULT NULL,
  `human_resources_13_8_1_C` varchar(5) DEFAULT NULL,
  `general_14_1_1_text` text,
  `general_14_1_1_A` varchar(5) DEFAULT NULL,
  `general_14_2_1_text` text,
  `general_14_2_1_A` varchar(5) DEFAULT NULL,
  `general_14_3_1_text` text,
  `general_14_3_1_A` varchar(5) DEFAULT NULL,
  `general_14_3_1_B_a` varchar(5) DEFAULT NULL,
  `general_14_3_1_B_b` varchar(5) DEFAULT NULL,
  `general_14_3_1_B_c` varchar(5) DEFAULT NULL,
  `general_14_3_1_B_d` varchar(5) DEFAULT NULL,
  `general_14_3_1_B_e` varchar(5) DEFAULT NULL,
  `general_14_3_1_C` varchar(5) DEFAULT NULL,
  `general_14_4_1_text` text,
  `general_14_4_1_A` varchar(5) DEFAULT NULL,
  `general_14_4_1_B` varchar(5) DEFAULT NULL,
  `general_14_5_1_text` text,
  `general_14_5_1_A` varchar(5) DEFAULT NULL,
  `general_14_5_1_B` varchar(5) DEFAULT NULL,
  `general_14_6_1_text` text,
  `general_14_6_1_A` varchar(5) DEFAULT NULL,
  `general_14_6_1_B` varchar(5) DEFAULT NULL,
  `general_14_7_1_text` text,
  `general_14_7_1_A` varchar(5) DEFAULT NULL,
  `general_14_7_1_B` varchar(5) DEFAULT NULL,
  `general_14_7_1_C` varchar(5) DEFAULT NULL,
  `general_14_8_1_text` text,
  `general_14_8_1_A` varchar(5) DEFAULT NULL,
  `general_14_8_1_B` varchar(5) DEFAULT NULL,
  `general_14_8_1_C_a` varchar(5) DEFAULT NULL,
  `general_14_8_1_C_b` varchar(5) DEFAULT NULL,
  `general_14_8_1_C_c` varchar(5) DEFAULT NULL,
  `general_14_8_1_C_d` varchar(5) DEFAULT NULL,
  `general_14_8_1_C_e` varchar(5) DEFAULT NULL,
  `general_14_8_1_D` varchar(5) DEFAULT NULL,
  `general_14_8_1_E` varchar(5) DEFAULT NULL,
  `general_14_8_1_F` varchar(5) DEFAULT NULL,
  `general_14_8_1_G` varchar(5) DEFAULT NULL,
  `general_14_9_1_text` text,
  `general_14_9_1_A` varchar(5) DEFAULT NULL,
  `general_14_9_1_B` varchar(5) DEFAULT NULL,

  PRIMARY KEY (`id`,`assessor_category`)
) ENGINE=MyISAM AUTO_INCREMENT=72 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records 
-- ----------------------------
